TriLite: TL::Distance Class Reference
TL::Distance Class Reference
#include <Distance.hpp>
Classes
class Tree
Static Public Member Functions
static double AsymmetricHausdorff (const Trimesh &mesh, const Trimesh &target_mesh, double precision)
Computes the asymmetric Hausdorff distance between two triangle meshes.
static double Hausdorff (const Trimesh &mesh1, const Trimesh &mesh2, double precision)
Computes the Hausdorff distance between two triangle meshes.
static double AsymmetricMeanEuclidean (const Trimesh &mesh, const Trimesh &target_mesh, double precision)
Computes the asymmetric mean Euclidean distance between two triangle meshes.
static double MeanEuclidean (const Trimesh &mesh1, const Trimesh &mesh2, double precision)
Computes the mean Euclidean distance between two triangle meshes.
Detailed Description
Definition at line 36 of file Distance.hpp.
Member Function Documentation
AsymmetricHausdorff()
double TL::Distance::AsymmetricHausdorff (const Trimesh & mesh, const Trimesh & target_mesh, double precision) static
Computes the asymmetric Hausdorff distance between two triangle meshes.
This function computes the asymmetric Hausdorff distance between two triangle meshes, mesh and target_mesh. The distance is calculated by finding the maximum distance from any point on mesh to its closest point on target_mesh.
Parameters
mesh The first triangle mesh from which points are sampled.
target_mesh The second triangle mesh to which distances are calculated.
precision Desired precision for the computed asymmetric Hausdorff distance, influencing the sampling density on the mesh.
Returns
double The computed asymmetric Hausdorff distance.
Definition at line 298 of file Distance.hpp.
{
  Tree tree(target_mesh);
  double hausdorff_d = 0;
  std::queue<std::pair<std::array<Vector3d, 3>, double>> q;
  for (F f : mesh.Faces()) {
    q.push(std::make_pair(
        std::array<Vector3d, 3>{mesh.VPosition(mesh.HStart(3 * f)),
                                mesh.VPosition(mesh.HStart(3 * f + 1)),
                                mesh.VPosition(mesh.HStart(3 * f + 2))},
        std::numeric_limits<double>::max()));
  }
  while (!q.empty()) {
    auto [tri, cur_max] = q.front();
    q.pop();
    if (cur_max < hausdorff_d + precision) {
      continue;
    }
    Vector3d bary = (tri[0] + tri[1] + tri[2]) / 3.;
    double bary_dist = tree.Distance(bary);
    hausdorff_d = std::max(hausdorff_d, bary_dist);
    double max_feasible =
        bary_dist + std::sqrt(std::max({(tri[0] - bary).squaredNorm(),
                                        (tri[1] - bary).squaredNorm(),
                                        (tri[2] - bary).squaredNorm()}));
    if (max_feasible > hausdorff_d + precision) {
      Vector3d a = (tri[0] + tri[1]) / 2.0;
      Vector3d b = (tri[1] + tri[2]) / 2.0;
      Vector3d c = (tri[2] + tri[0]) / 2.0;
      for (std::array<Vector3d, 3> sub_tri :
           std::array<std::array<Vector3d, 3>, 4>{
               std::array<Vector3d, 3>{a, b, c},
               std::array<Vector3d, 3>{tri[0], a, c},
               std::array<Vector3d, 3>{tri[1], b, a},
               std::array<Vector3d, 3>{tri[2], c, b}}) {
        q.push(std::make_pair(std::move(sub_tri), max_feasible));
      }
    }
  }
  return hausdorff_d;
}
References TL::Distance::Tree::Distance(), TL::Trimesh::Faces(), TL::Trimesh::HStart(), and TL::Trimesh::VPosition().
Referenced by Hausdorff().
AsymmetricMeanEuclidean()
double TL::Distance::AsymmetricMeanEuclidean (const Trimesh & mesh, const Trimesh & target_mesh, double precision) static
Computes the asymmetric mean Euclidean distance between two triangle meshes.
This function computes the asymmetric mean Euclidean distance between two triangle meshes, mesh1 and mesh2. The distance is calculated by sampling points from mesh and finding the closest points on target_mesh.
Parameters
mesh The first triangle mesh from which points are sampled.
target_mesh The second triangle mesh to which distances are calculated.
precision Desired precision for the computed asymmetric mean Euclidean distance, influencing the sampling density on the mesh.
Returns
double The computed asymmetric mean Euclidean distance.
Definition at line 346 of file Distance.hpp.
{
  // 18 / (2\sqrt{3} + \ln(\sqrt{3} + 2));
  const double ratio_precision_to_length = 3.764855876524;
  double distance = 0;
  double sum_area = 0;
  Tree distance_tree(target_mesh);
  double sq_length = pow(precision * ratio_precision_to_length, 2);
  std::function<void(std::array<Vector3d, 3>&&, double)> process_triangle =
      [&](std::array<Vector3d, 3>&& tri, double area) {
        if (std::max({(tri[1] - tri[0]).squaredNorm(),
                      (tri[2] - tri[1]).squaredNorm(),
                      (tri[0] - tri[2]).squaredNorm()}) <= sq_length) {
          distance +=
              area * distance_tree.Distance((tri[0] + tri[1] + tri[2]) / 3.0);
          return;
        }
        area /= 4.0;
        Vector3d a = (tri[0] + tri[1]) / 2.0;
        Vector3d b = (tri[1] + tri[2]) / 2.0;
        Vector3d c = (tri[2] + tri[0]) / 2.0;
        for (std::array<Vector3d, 3> sub_tri :
             std::array<std::array<Vector3d, 3>, 4>{
                 std::array<Vector3d, 3>{a, b, c},
                 std::array<Vector3d, 3>{tri[0], a, c},
                 std::array<Vector3d, 3>{tri[1], b, a},
                 std::array<Vector3d, 3>{tri[2], c, b}}) {
          process_triangle(std::move(sub_tri), area);
        }
      };
  for (TL::F f : mesh.Faces()) {
    std::array<Vector3d, 3> tri{mesh.VPosition(mesh.HStart(3 * f)),
                                mesh.VPosition(mesh.HStart(3 * f + 1)),
                                mesh.VPosition(mesh.HStart(3 * f + 2))};
    double area = mesh.FArea(f);
    process_triangle(std::move(tri), area);
    sum_area += area;
  }
  return distance / sum_area;
}
References TL::Distance::Tree::Distance(), TL::Trimesh::Faces(), TL::Trimesh::FArea(), TL::Trimesh::HStart(), and TL::Trimesh::VPosition().
Referenced by MeanEuclidean().
Hausdorff()
double TL::Distance::Hausdorff (const Trimesh & mesh1, const Trimesh & mesh2, double precision) static
Computes the Hausdorff distance between two triangle meshes.
This function computes the Hausdorff distance between two triangle meshes, mesh1 and mesh2. The distance is calculated as the maximum of the asymmetric Hausdorff distances computed in both directions: from mesh1 to mesh2 and from mesh2 to mesh1.
Parameters
mesh1 The first triangle mesh.
mesh2 The second triangle mesh.
precision Desired precision for the computed Hausdorff distance, influencing the sampling density on the mesh.
Returns
double The computed Hausdorff distance.
Definition at line 341 of file Distance.hpp.
{
  return std::max(AsymmetricHausdorff(mesh1, mesh2, precision),
                  AsymmetricHausdorff(mesh2, mesh1, precision));
}
References AsymmetricHausdorff().
MeanEuclidean()
double TL::Distance::MeanEuclidean (const Trimesh & mesh1, const Trimesh & mesh2, double precision) static
Computes the mean Euclidean distance between two triangle meshes.
This function computes the mean Euclidean distance between two triangle meshes, mesh1 and mesh2. The distance is calculated by averaging the asymmetric mean Euclidean distances computed in both directions: from mesh1 to mesh2 and from mesh2 to mesh1.
Parameters
mesh1 The first triangle mesh.
mesh2 The second triangle mesh.
precision Desired precision for the computed mean Euclidean distance, influencing the sampling density on the mesh.
Returns
double The computed mean Euclidean distance.
Definition at line 388 of file Distance.hpp.
{
  double distance1 = Distance::AsymmetricMeanEuclidean(mesh1, mesh2, precision);
  double distance2 = Distance::AsymmetricMeanEuclidean(mesh2, mesh1, precision);
  return (distance1 + distance2) / 2.0;
}
References AsymmetricMeanEuclidean().
The documentation for this class was generated from the following file:
/home/saumz/Documents/projects/TriLite/TriLite/Modules/Distance.hpp