TriLite: TL::Trimesh Class Reference
TL::Trimesh Class Reference
Represents a triangle mesh using a half-edge data structure.
#include <Trimesh.hpp>
Public Member Functions
Trimesh ()
Constructs an empty Trimesh.
Trimesh (const std::vector< std::variant< V, Vector3d > > &tri_points)
Constructs a Trimesh from a vector of vertices and their positions.
Trimesh (const Trimesh &other)
Copy constructor for Trimesh.
Trimesh & operator= (const Trimesh &other)
Assignment operator for Trimesh.
H NumHalfedges () const
Returns the number of halfedges in the mesh.
V NumVertices () const
Returns the number of vertices in the mesh.
F NumFaces () const
Returns the number of faces in the mesh.
std::ranges::iota_view< H, H > Halfedges () const
Returns a view of the halfedges in the mesh.
std::ranges::iota_view< V, V > Vertices () const
Returns a view of the vertices in the mesh.
std::ranges::iota_view< F, F > Faces () const
Returns a view of the faces in the mesh.
std::ranges::ref_view< std::vector< Vector3d > > Positions ()
Returns a view of the vertex positions.
std::ranges::ref_view< const std::vector< Vector3d > > Positions () const
Returns a constant view of the vertex positions.
H HNext (H h) const
Returns the next halfedge in the face.
H HPrev (H h) const
Returns the previous halfedge in the face.
V HStart (H h) const
Returns the starting vertex of the halfedge.
V HEnd (H h) const
Returns the ending vertex of the halfedge.
F HFace (H h) const
Returns the face associated with the halfedge.
H HOpposite (H h) const
Returns the opposite halfedge of the given halfedge.
H HNextAroundStart (H h) const
Returns the next halfedge around the starting vertex.
H HPrevAroundStart (H h) const
Returns the previous halfedge around the starting vertex.
H HNextAroundEnd (H h) const
Returns the next halfedge around the ending vertex.
H HPrevAroundEnd (H h) const
Returns the previous halfedge around the ending vertex.
Vector3d HGeometry (H h) const
Returns the geometric vector of the halfedge.
Vector3d HCentroid (H h) const
Computes the centroid (mean) position of a specific halfedge.
std::generator< H > HConnectionsAroundStart (H st_h) const
Returns a generator for the halfedges connected around the starting vertex.
std::generator< H > HHalfedgesAroundHole (H st_h) const
Returns a generator for the halfedges around a hole.
double HLength (H h) const
Returns the length of the halfedge.
H VStarting (V v) const
Returns the starting halfedge of the vertex.
H VEnding (V v) const
Returns the ending halfedge of the vertex.
std::generator< H > VStartings (V v) const
Returns a generator for the starting halfedges of the vertex.
std::generator< H > VEndings (V v) const
Returns a generator for the ending halfedges of the vertex.
auto VFaces (V v) const
Returns a view of the faces connected to the vertex.
Vector3d & VPosition (V v)
Returns the position of the vertex.
const Vector3d & VPosition (V v) const
Returns the constant position of the vertex.
Vector3d VNormal (V v) const
Returns the normal vector of the vertex.
size_t VValence (V v) const
Returns the valence (degree) of the vertex.
bool VIsManifold (V v) const
Checks if the vertex is manifold.
H FHalfedge (F f) const
Returns the halfedge associated with the face.
std::ranges::iota_view< H, H > FHalfedges (F f) const
Returns a view of the halfedges of the face.
std::generator< F > FNeighbors (F f) const
Returns a generator for neighboring faces of a given face.
auto FVertices (F f) const
Returns a view of the vertices of the face.
auto FPositions (F f) const
Returns a view of the vertex positions of the face.
Vector3d FNormal (F f) const
Returns the normal vector of the face.
double FArea (F f) const
Returns the area of the face.
std::pair< Vector3d, Vector3d > FBoundingBox (F f) const
Computes the axis-aligned bounding box (AABB) of a specific face.
Vector3d FCentroid (F f) const
Computes the centroid (mean) of a specific face.
std::generator< H > EdgeHalfedges (H h) const
Returns a generator for the halfedges forming an edge.
auto EdgeFaces (H h) const
Returns a view of the faces connected by an edge.
bool EdgeIsManifold (H h) const
Checks if the edge is manifold.
auto BoundaryHalfedges () const
Returns a view of the boundary halfedges.
std::pair< Vector3d, Vector3d > BoundingBox () const
Computes the axis-aligned bounding box (AABB) of the entire mesh.
Vector3d Centroid () const
Computes the centroid (mean) of all vertices in the mesh.
F AddFace (const std::array< std::variant< V, Vector3d >, 3 > &triangle)
Adds a face to the mesh.
std::vector< V > RemoveFace (F f)
Removes a face from the mesh.
std::vector< V > RemoveFaces (std::vector< F > f_set)
Removes multiple face indices from the mesh.
std::pair< std::vector< F >, std::vector< V > > CollapseEdge (H h)
Collapses an edge and merges its vertices.
void SplitEdge (H h)
Splits an edge and the incident faces.
void FlipHalfedgeWithOpposite (H h)
Flips an edge shared by two adjacent triangles.
void DisconnectFace (F f)
Disconnects a face from the mesh, converting it to a boundary face.
void DisconnectFacesUntilManifoldEdges ()
Disconnects faces until all edges are manifold.
void DisconnectFacesUntilManifoldVertices ()
Disconnects faces until all vertices are manifold.
void DisconnectFacesUntilManifold ()
Disconnects faces until both edges and vertices are manifold.
template<MeshComponent C, typename T >
std::ranges::ref_view< std::vector< T > > CreateAttribute (const std::string &key)
Creates an attribute for a specified mesh component.
template<MeshComponent C, typename T >
std::ranges::ref_view< std::vector< T > > GetAttribute (const std::string &key)
Retrieves an attribute for a specified mesh component.
template<MeshComponent C>
void EraseAttribute (const std::string &key)
Erases an attribute for a specified mesh component.
Detailed Description
Represents a triangle mesh using a half-edge data structure.
Definition at line 45 of file Trimesh.hpp.
Constructor & Destructor Documentation
Trimesh() [1/3]
TL::Trimesh::Trimesh ()
Constructs an empty Trimesh.
Definition at line 530 of file Trimesh.hpp.
{}
Trimesh() [2/3]
TL::Trimesh::Trimesh (const std::vector< std::variant< V, Vector3d > > & tri_points)
Constructs a Trimesh from a vector of vertices and their positions.
Parameters
tri_points Vector of vertices and positions defining the triangle mesh.
Definition at line 531 of file Trimesh.hpp.
    : Trimesh() {
  for (V v = 0; v < (V)tri_points.size(); v += 3) {
    AddFace({tri_points[v], tri_points[v + 1], tri_points[v + 2]});
  }
}
References AddFace().
Trimesh() [3/3]
TL::Trimesh::Trimesh (const Trimesh & other)
Copy constructor for Trimesh.
Parameters
other The Trimesh object to copy.
Definition at line 537 of file Trimesh.hpp.
    : hStart_(other.hStart_),
      hCoStart_(other.hCoStart_),
      vStart_(other.vStart_),
      position_(other.position_) {
  for (int i = 0; i < 3; ++i) {
    for (const auto& [key, wrapper] : other.attributes_[i]) {
      attributes_[i][key] = wrapper->clone();
    }
  }
}
Member Function Documentation
AddFace()
F TL::Trimesh::AddFace (const std::array< std::variant< V, Vector3d >, 3 > & triangle)
Adds a face to the mesh.
Parameters
triangle Array of three vertices or positions defining the triangle.
Returns
The face index.
Definition at line 775 of file Trimesh.hpp.
{
  for (int i = 0; i < 3; i++) {
    if (std::holds_alternative<V>(triangle[i])) {
      for (int j = 0; j < i; j++) {
        if (triangle[i] == triangle[j]) {
          throw std::invalid_argument(
              "AddFace called with a degenerated triangle parameter");
        }
      }
    }
  }
  for (const auto& [key, f_attr] : attributes_[kFace]) {
    f_attr->IncrementSize();
  }
  H h_offset = hStart_.size();
  for (const auto& elem : triangle) {
    H h = hStart_.size();
    V v = position_.size();
    if (std::holds_alternative<V>(elem)) {
      v = std::get<V>(elem);
    } else {
      for (const auto& [key, v_attr] : attributes_[kVertex]) {
        v_attr->IncrementSize();
      }
      position_.push_back(std::get<Vector3d>(elem));
      vStart_.push_back(kInvalidId);
    }
    for (const auto& [key, h_attr] : attributes_[kHalfedge]) {
      h_attr->IncrementSize();
    }
    hStart_.push_back(v);
    hCoStart_.push_back(vStart_.at(v));
    vStart_.at(v) = h;
  }
  return HFace(h_offset);
}
References HFace(), TL::kFace, TL::kHalfedge, TL::kInvalidId, and TL::kVertex.
Referenced by DisconnectFace(), TL::Processing::FillMeshHoles(), FlipHalfedgeWithOpposite(), SplitEdge(), and Trimesh().
BoundaryHalfedges()
auto TL::Trimesh::BoundaryHalfedges () const inline
Returns a view of the boundary halfedges.
Returns
A view of the boundary halfedge indices.
Definition at line 748 of file Trimesh.hpp.
{
  return std::views::filter(Halfedges(),
                            [this](H h) { return HOpposite(h) == kInvalidId; });
}
References Halfedges(), HOpposite(), and TL::kInvalidId.
Referenced by TL::Processing::FillMeshHoles().
BoundingBox()
std::pair< Vector3d, Vector3d > TL::Trimesh::BoundingBox () const
Computes the axis-aligned bounding box (AABB) of the entire mesh.
Returns
A pair of Vector3d, where the first element is the minimum corner of the bounding box and the second element is the maximum corner of the bounding box.
Exceptions
std::runtime_error if the mesh has no vertices.
Definition at line 752 of file Trimesh.hpp.
{
  if (position_.empty()) {
    throw std::runtime_error("Mesh has no vertices.");
  }
  Vector3d min = position_.front();
  Vector3d max = min;
  for (const auto& pos : position_) {
    min = min.cwiseMin(pos);
    max = max.cwiseMax(pos);
  }
  return {min, max};
}
Centroid()
Vector3d TL::Trimesh::Centroid () const
Computes the centroid (mean) of all vertices in the mesh.
Returns
A Vector3d representing the centroid of all vertices in the mesh.
Exceptions
std::runtime_error if the mesh has no vertices.
Definition at line 764 of file Trimesh.hpp.
{
  if (position_.empty()) {
    throw std::runtime_error("Mesh has no vertices.");
  }
  Vector3d centroid = Vector3d::Zero();
  for (const auto& pos : position_) {
    centroid += pos;
  }
  centroid /= static_cast<double>(position_.size());
  return centroid;
}
CollapseEdge()
std::pair< std::vector< F >, std::vector< V > > TL::Trimesh::CollapseEdge (H h)
Collapses an edge and merges its vertices.
Parameters
h The halfedge index.
Returns
A pair of vectors containing the removed faces and vertices.
Definition at line 891 of file Trimesh.hpp.
{
  std::vector<V> removed_vertices;
  std::vector<F> removed_faces = EdgeFaces(h) | std::ranges::to<std::vector>();
  std::array<V, 2> verts = {HStart(h), HEnd(h)};
  Vector3d midpoint = (VPosition(verts[0]) + VPosition(verts[1])) / 2.0;
  V last_vert_id = NumVertices() - 1;
  for (size_t i = 0; i < removed_faces.size(); i++) {
    std::vector<V> rm_verts = RemoveFace(removed_faces[i]);
    removed_vertices.insert(removed_vertices.end(), rm_verts.begin(),
                            rm_verts.end());
    for (size_t j = i + 1; j < removed_faces.size(); j++) {
      if (removed_faces[j] == NumFaces()) {
        removed_faces[j] = removed_faces[i];
      }
    }
  }
  for (const V& rem_v : removed_vertices) {
    for (V& v : verts) {
      if (v == rem_v) {
        v = kInvalidId;
      } else if (v == last_vert_id) {
        v = rem_v;
      }
    }
    last_vert_id--;
  }
  if (verts[0] == kInvalidId) {
    std::swap(verts[0], verts[1]);
  }
  if (verts[0] == kInvalidId) {
    return std::make_pair(std::move(removed_faces),
                          std::move(removed_vertices));
  }
  position_[verts[0]] = midpoint;
  std::vector<H> v_starts;
  for (V vert : verts) {
    if (vert != kInvalidId) {
      for (H he : VStartings(vert)) {
        v_starts.push_back(he);
      }
    }
  }
  std::sort(v_starts.begin(), v_starts.end());
  vStart_[verts[0]] = kInvalidId;
  for (H he : v_starts) {
    hStart_[he] = verts[0];
    hCoStart_[he] = vStart_[verts[0]];
    vStart_[verts[0]] = he;
  }
  if (verts[1] != kInvalidId) {
    removed_vertices.push_back(verts[1]);
    if (verts[1] != vStart_.size() - 1) {
      for (H he : VStartings(vStart_.size() - 1)) {
        hStart_[he] = verts[1];
      }
      vStart_[verts[1]] = vStart_.back();
      position_[verts[1]] = std::move(position_.back());
    }
    vStart_.pop_back();
    position_.pop_back();
    for (const auto& [key, v_attr] : attributes_[kVertex]) {
      v_attr->ReplaceErase(verts[1]);
    }
  }
  return std::make_pair(std::move(removed_faces), std::move(removed_vertices));
}
References EdgeFaces(), HEnd(), HStart(), TL::kInvalidId, TL::kVertex, NumFaces(), NumVertices(), RemoveFace(), VPosition(), and VStartings().
Referenced by TL::Processing::DecimateMesh().
CreateAttribute()
template<MeshComponent C, typename T > std::ranges::ref_view< std::vector< T > > TL::Trimesh::CreateAttribute (const std::string & key)
Creates an attribute for a specified mesh component.
Template Parameters
C The mesh component (halfedge, vertex, or face).
T The attribute type.
Parameters
key The key identifying the attribute.
Returns
A reference view of the created attribute.
Exceptions
std::invalid_argument if the attribute already exists.
Definition at line 1037 of file Trimesh.hpp.
{
  if (attributes_[C].find(key) != attributes_[C].end()) {
    throw std::invalid_argument("Attribute already exists.");
  }
  size_t N = C == kHalfedge ? NumHalfedges()
             : C == kVertex ? NumVertices()
                            : NumFaces();
  attributes_[C][key] =
      std::make_unique<ContainerWrapper<std::vector<T>>>(std::vector<T>(N));
  return GetAttribute<C, T>(key);
}
References GetAttribute(), TL::kHalfedge, TL::kVertex, NumFaces(), NumHalfedges(), and NumVertices().
DisconnectFace()
void TL::Trimesh::DisconnectFace (F f)
Disconnects a face from the mesh, converting it to a boundary face.
Parameters
f The face index.
Definition at line 989 of file Trimesh.hpp.
{
  AddFace({VPosition(HStart(3 * f)), VPosition(HStart(3 * f + 1)),
           VPosition(HStart(3 * f + 2))});
  RemoveFace(f);
}
References AddFace(), HStart(), RemoveFace(), and VPosition().
Referenced by DisconnectFacesUntilManifoldEdges(), and DisconnectFacesUntilManifoldVertices().
DisconnectFacesUntilManifold()
void TL::Trimesh::DisconnectFacesUntilManifold ()
Disconnects faces until both edges and vertices are manifold.
Definition at line 1032 of file Trimesh.hpp.
{
  DisconnectFacesUntilManifoldEdges();
  DisconnectFacesUntilManifoldVertices();
}
References DisconnectFacesUntilManifoldEdges(), and DisconnectFacesUntilManifoldVertices().
Referenced by TL::Processing::PrintabilityHeuristics().
DisconnectFacesUntilManifoldEdges()
void TL::Trimesh::DisconnectFacesUntilManifoldEdges ()
Disconnects faces until all edges are manifold.
Definition at line 994 of file Trimesh.hpp.
{
  for (F f : std::views::reverse(Faces())) {
    for (H h : FHalfedges(f)) {
      if (!EdgeIsManifold(h)) {
        DisconnectFace(f);
        break;
      }
    }
  }
}
References DisconnectFace(), EdgeIsManifold(), Faces(), and FHalfedges().
Referenced by DisconnectFacesUntilManifold().
DisconnectFacesUntilManifoldVertices()
void TL::Trimesh::DisconnectFacesUntilManifoldVertices ()
Disconnects faces until all vertices are manifold.
Definition at line 1004 of file Trimesh.hpp.
{
  std::queue<V> q;
  for (V v : Vertices()) {
    if (!VIsManifold(v)) {
      q.push(v);
    }
  }
  while (!q.empty()) {
    V v = q.front();
    q.pop();
    if (VIsManifold(v)) {
      continue;
    }
    std::unordered_set<V> s;
    for (H h : HConnectionsAroundStart(VStarting(v))) {
      s.insert(h);
    }
    for (H h : VStartings(v)) {
      if (!s.count(h)) {
        F f{HFace(h)};
        for (V u : FVertices(f)) {
          q.push(u);
        }
        DisconnectFace(f);
      }
    }
  }
}
References DisconnectFace(), FVertices(), HConnectionsAroundStart(), HFace(), Vertices(), VIsManifold(), VStarting(), and VStartings().
Referenced by DisconnectFacesUntilManifold().
EdgeFaces()
auto TL::Trimesh::EdgeFaces (H h) const
Returns a view of the faces connected by an edge.
Parameters
h The halfedge index.
Returns
A view of the face indices.
Definition at line 736 of file Trimesh.hpp.
{
  return std::views::transform(EdgeHalfedges(h),
                               [this](H h) { return HFace(h); });
}
References EdgeHalfedges(), and HFace().
Referenced by CollapseEdge().
EdgeHalfedges()
std::generator< H > TL::Trimesh::EdgeHalfedges (H h) const
Returns a generator for the halfedges forming an edge.
Parameters
h The halfedge index.
Returns
A generator for the halfedges forming the edge.
Definition at line 724 of file Trimesh.hpp.
{
  for (H he : VStartings(HStart(h))) {
    if (HEnd(he) == HEnd(h)) {
      co_yield (he);
    }
  }
  for (H he : VStartings(HEnd(h))) {
    if (HEnd(he) == HStart(h)) {
      co_yield (he);
    }
  }
}
References HEnd(), HStart(), and VStartings().
Referenced by EdgeFaces(), EdgeIsManifold(), and SplitEdge().
EdgeIsManifold()
bool TL::Trimesh::EdgeIsManifold (H h) const
Checks if the edge is manifold.
Parameters
h The halfedge index.
Returns
True if the edge is manifold, false otherwise.
Definition at line 740 of file Trimesh.hpp.
{
  for (H g : EdgeHalfedges(h)) {
    if (g != h && g != HOpposite(h)) {
      return false;
    }
  }
  return true;
}
References EdgeHalfedges(), and HOpposite().
Referenced by DisconnectFacesUntilManifoldEdges(), HConnectionsAroundStart(), and HHalfedgesAroundHole().
EraseAttribute()
template<MeshComponent C> void TL::Trimesh::EraseAttribute (const std::string & key)
Erases an attribute for a specified mesh component.
Template Parameters
C The mesh component (halfedge, vertex, or face).
Parameters
key The key identifying the attribute.
Exceptions
std::invalid_argument if the attribute does not exist.
Definition at line 1064 of file Trimesh.hpp.
{
  auto it = attributes_[C].find(key);
  if (it == attributes_[C].end()) {
    throw std::invalid_argument("Attribute does not exist.");
  }
  attributes_[C].erase(it);
}
References GetAttribute().
Faces()
std::ranges::iota_view< F, F > TL::Trimesh::Faces () const inline
Returns a view of the faces in the mesh.
Returns
A range of face indices.
Definition at line 574 of file Trimesh.hpp.
{
  return std::views::iota(F{0}, F{NumFaces()});
}
References NumFaces().
Referenced by TL::Distance::AsymmetricHausdorff(), TL::Distance::AsymmetricMeanEuclidean(), DisconnectFacesUntilManifoldEdges(), and TL::Distance::Tree::Tree().
FArea()
double TL::Trimesh::FArea (F f) const inline
Returns the area of the face.
Parameters
f The face index.
Returns
The area of the face.
Definition at line 708 of file Trimesh.hpp.
{
  return 0.5 * HGeometry(3 * f).cross(HGeometry(3 * f + 2)).norm();
}
References HGeometry().
Referenced by TL::Distance::AsymmetricMeanEuclidean().
FBoundingBox()
std::pair< Vector3d, Vector3d > TL::Trimesh::FBoundingBox (F f) const inline
Computes the axis-aligned bounding box (AABB) of a specific face.
Parameters
f The face index for which to compute the bounding box.
Returns
A pair of Vector3d, where the first element is the minimum corner of the bounding box and the second element is the maximum corner of the bounding box.
Definition at line 711 of file Trimesh.hpp.
{
  return {VPosition(HStart(3 * f))
              .cwiseMin(VPosition(HStart(3 * f + 1)))
              .cwiseMin(VPosition(HStart(3 * f + 2))),
          VPosition(HStart(3 * f))
              .cwiseMax(VPosition(HStart(3 * f + 1)))
              .cwiseMax(VPosition(HStart(3 * f + 2)))};
}
References HStart(), and VPosition().
FCentroid()
Vector3d TL::Trimesh::FCentroid (F f) const inline
Computes the centroid (mean) of a specific face.
Parameters
f The face index for which to compute the centroid.
Returns
A Vector3d representing the centroid of the specified face.
Definition at line 719 of file Trimesh.hpp.
{
  return (VPosition(HStart(3 * f)) + VPosition(HStart(3 * f + 1)) +
          VPosition(HStart(3 * f + 2))) /
         3.0;
}
References HStart(), and VPosition().
FHalfedge()
H TL::Trimesh::FHalfedge (F f) const inline
Returns the halfedge associated with the face.
Parameters
f The face index.
Returns
The halfedge index.
Definition at line 682 of file Trimesh.hpp.
{
  assert(f < NumFaces());
  return 3 * f;
}
References NumFaces().
Referenced by FHalfedges().
FHalfedges()
std::ranges::iota_view< H, H > TL::Trimesh::FHalfedges (F f) const inline
Returns a view of the halfedges of the face.
Parameters
f The face index.
Returns
A range of halfedge indices.
Definition at line 686 of file Trimesh.hpp.
{
  return std::views::iota(FHalfedge(f), H{3 * f + 3});
}
References FHalfedge().
Referenced by DisconnectFacesUntilManifoldEdges(), FNeighbors(), FVertices(), and RemoveFace().
FlipHalfedgeWithOpposite()
void TL::Trimesh::FlipHalfedgeWithOpposite (H h)
Flips an edge shared by two adjacent triangles.
Parameters
h The halfedge index representing the edge to flip.
Definition at line 971 of file Trimesh.hpp.
{
  H hopp = HOpposite(h);
  if (hopp == kInvalidId) {
    throw std::invalid_argument("h param needs opposite to perform edge flip");
  }
  std::array<V, 4> verts{HStart(h), HEnd(h), HEnd(HNext(h)), HEnd(HNext(hopp))};
  if (verts[2] == verts[3]) {
    throw std::invalid_argument("Opp faces are identical, edge flip fails");
  }
  std::array<std::variant<V, Vector3d>, 3> tri = {verts[3], verts[2], verts[0]};
  std::rotate(tri.begin(), tri.begin() + (3 - (h % 3)) % 3, tri.end());
  AddFace(tri);
  RemoveFace(HFace(h));
  tri = {verts[2], verts[3], verts[1]};
  std::rotate(tri.begin(), tri.begin() + (3 - (hopp % 3)) % 3, tri.end());
  AddFace(tri);
  RemoveFace(HFace(hopp));
}
References AddFace(), HEnd(), HFace(), HNext(), HOpposite(), HStart(), TL::kInvalidId, and RemoveFace().
FNeighbors()
std::generator< F > TL::Trimesh::FNeighbors (F f) const
Returns a generator for neighboring faces of a given face.
Parameters
f The face index for which to find neighboring faces.
Returns
std::generator<F> A generator for the indices of neighboring faces.
Definition at line 689 of file Trimesh.hpp.
{
  for (H h : FHalfedges(f)) {
    H opp = HOpposite(h);
    if (opp != kInvalidId) {
      co_yield HFace(opp);
    }
  }
}
References FHalfedges(), HFace(), HOpposite(), and TL::kInvalidId.
FNormal()
Vector3d TL::Trimesh::FNormal (F f) const inline
Returns the normal vector of the face.
Parameters
f The face index.
Returns
The normal vector.
Definition at line 705 of file Trimesh.hpp.
{
  return HGeometry(3 * f).cross(-HGeometry(3 * f + 2)).normalized();
}
References HGeometry().
Referenced by VNormal().
FPositions()
auto TL::Trimesh::FPositions (F f) const inline
Returns a view of the vertex positions of the face.
Parameters
f The face index.
Returns
A view of the vertex positions.
Definition at line 701 of file Trimesh.hpp.
{
  return std::views::transform(FVertices(f),
                               [this](V v) { return VPosition(v); });
}
References FVertices(), and VPosition().
FVertices()
auto TL::Trimesh::FVertices (F f) const inline
Returns a view of the vertices of the face.
Parameters
f The face index.
Returns
A view of the vertex indices.
Definition at line 697 of file Trimesh.hpp.
{
  return std::views::transform(FHalfedges(f),
                               [this](H h) { return HStart(h); });
}
References FHalfedges(), and HStart().
Referenced by DisconnectFacesUntilManifoldVertices(), FPositions(), and TL::Distance::Tree::Tree().
GetAttribute()
template<MeshComponent C, typename T > std::ranges::ref_view< std::vector< T > > TL::Trimesh::GetAttribute (const std::string & key)
Retrieves an attribute for a specified mesh component.
Template Parameters
C The mesh component (halfedge, vertex, or face).
T The attribute type.
Parameters
key The key identifying the attribute.
Returns
A reference view of the attribute.
Exceptions
std::invalid_argument if the attribute does not exist or type does not match.
Definition at line 1050 of file Trimesh.hpp.
{
  auto it = attributes_[C].find(key);
  if (it == attributes_[C].end()) {
    throw std::invalid_argument("Attribute does not exist.");
  }
  auto containerPtr =
      dynamic_cast<ContainerWrapper<std::vector<T>>*>(it->second.get());
  if (!containerPtr) {
    throw std::invalid_argument("Attribute exists but type does not match.");
  }
  return std::views::all(containerPtr->container_);
}
References GetAttribute().
Referenced by CreateAttribute(), EraseAttribute(), and GetAttribute().
Halfedges()
std::ranges::iota_view< H, H > TL::Trimesh::Halfedges () const inline
Returns a view of the halfedges in the mesh.
Returns
A range of halfedge indices.
Definition at line 568 of file Trimesh.hpp.
{
  return std::views::iota(H{0}, H{NumHalfedges()});
}
References NumHalfedges().
Referenced by BoundaryHalfedges(), TL::Processing::DecimateMesh(), and TL::Processing::PrintabilityHeuristics().
HCentroid()
Vector3d TL::Trimesh::HCentroid (H h) const inline
Computes the centroid (mean) position of a specific halfedge.
Parameters
h The halfedge index for which to compute the centroid.
Returns
A Vector3d representing the centroid of the specified halfedge.
Definition at line 617 of file Trimesh.hpp.
{
  return (VPosition(HEnd(h)) + VPosition(HStart(h))) / 2.0;
}
References HEnd(), HStart(), and VPosition().
Referenced by SplitEdge().
HConnectionsAroundStart()
std::generator< H > TL::Trimesh::HConnectionsAroundStart (H st_h) const
Returns a generator for the halfedges connected around the starting vertex.
Parameters
st_h The starting halfedge.
Returns
A generator for the connected halfedges.
Definition at line 620 of file Trimesh.hpp.
{
  H h = st_h;
  while (HOpposite(h) != kInvalidId) {
    assert(EdgeIsManifold(h));
    h = HPrevAroundStart(h);
    if (h == st_h) {
      break;
    }
  }
  st_h = h;
  do {
    assert(EdgeIsManifold(h));
    co_yield h;
    h = HNextAroundStart(h);
  } while (h != st_h && h != kInvalidId);
}
References EdgeIsManifold(), HNextAroundStart(), HOpposite(), HPrevAroundStart(), and TL::kInvalidId.
Referenced by DisconnectFacesUntilManifoldVertices(), TL::Processing::FillMeshHoles(), and VIsManifold().
HEnd()
V TL::Trimesh::HEnd (H h) const inline
Returns the ending vertex of the halfedge.
Parameters
h The halfedge index.
Returns
The ending vertex index.
Definition at line 593 of file Trimesh.hpp.
{ return HStart(HNext(h)); }
References HNext(), and HStart().
Referenced by CollapseEdge(), TL::Processing::DecimateMesh(), EdgeHalfedges(), FlipHalfedgeWithOpposite(), HCentroid(), HGeometry(), HOpposite(), SplitEdge(), and TL::Processing::TaubinSmoothing().
HFace()
F TL::Trimesh::HFace (H h) const inline
Returns the face associated with the halfedge.
Parameters
h The halfedge index.
Returns
The face index.
Definition at line 594 of file Trimesh.hpp.
{
  assert(h < NumHalfedges());
  return h / 3;
}
References NumHalfedges().
Referenced by AddFace(), DisconnectFacesUntilManifoldVertices(), EdgeFaces(), FlipHalfedgeWithOpposite(), FNeighbors(), SplitEdge(), and VFaces().
HGeometry()
Vector3d TL::Trimesh::HGeometry (H h) const inline
Returns the geometric vector of the halfedge.
Parameters
h The halfedge index.
Returns
The geometric vector.
Definition at line 614 of file Trimesh.hpp.
{
  return VPosition(HEnd(h)) - VPosition(HStart(h));
}
References HEnd(), HStart(), and VPosition().
Referenced by FArea(), TL::Processing::FillMeshHoles(), FNormal(), and HLength().
HHalfedgesAroundHole()
std::generator< H > TL::Trimesh::HHalfedgesAroundHole (H st_h) const
Returns a generator for the halfedges around a hole.
Parameters
st_h The starting halfedge of the hole.
Returns
A generator for the halfedges around the hole.
Definition at line 636 of file Trimesh.hpp.
{
  assert(HOpposite(st_h) == kInvalidId);
  H h = st_h;
  do {
    co_yield h;
    h = HNext(h);
    while (HOpposite(h) != kInvalidId) {
      assert(EdgeIsManifold(h));
      h = HPrevAroundStart(h);
    }
  } while (h != st_h);
}
References EdgeIsManifold(), HNext(), HOpposite(), HPrevAroundStart(), and TL::kInvalidId.
Referenced by TL::Processing::FillMeshHoles().
HLength()
double TL::Trimesh::HLength (H h) const inline
Returns the length of the halfedge.
Parameters
h The halfedge index.
Returns
The length of the halfedge.
Definition at line 648 of file Trimesh.hpp.
{ return HGeometry(h).norm(); }
References HGeometry().
Referenced by TL::Processing::DecimateMesh(), and TL::Processing::PrintabilityHeuristics().
HNext()
H TL::Trimesh::HNext (H h) const inline
Returns the next halfedge in the face.
Parameters
h The current halfedge.
Returns
The next halfedge in the face.
Definition at line 584 of file Trimesh.hpp.
{
  assert(h < NumHalfedges());
  return h - h % 3 + (h + 1) % 3;
}
References NumHalfedges().
Referenced by FlipHalfedgeWithOpposite(), HEnd(), HHalfedgesAroundHole(), HOpposite(), HPrevAroundEnd(), and HPrevAroundStart().
HNextAroundEnd()
H TL::Trimesh::HNextAroundEnd (H h) const inline
Returns the next halfedge around the ending vertex.
Parameters
h The current halfedge.
Returns
The next halfedge around the ending vertex.
Definition at line 610 of file Trimesh.hpp.
{
  return HOpposite(h) == kInvalidId ? kInvalidId : HPrev(HOpposite(h));
}
References HOpposite(), HPrev(), and TL::kInvalidId.
HNextAroundStart()
H TL::Trimesh::HNextAroundStart (H h) const inline
Returns the next halfedge around the starting vertex.
Parameters
h The current halfedge.
Returns
The next halfedge around the starting vertex.
Definition at line 606 of file Trimesh.hpp.
{ return HOpposite(HPrev(h)); }
References HOpposite(), and HPrev().
Referenced by HConnectionsAroundStart().
HOpposite()
H TL::Trimesh::HOpposite (H h) const
Returns the opposite halfedge of the given halfedge.
Parameters
h The halfedge index.
Returns
The opposite halfedge index or kInvalidId if it does not exist.
Definition at line 598 of file Trimesh.hpp.
{
  for (H nh : VStartings(HStart(HNext(h)))) {
    if (HEnd(nh) == HStart(h) && HStart(nh) == HEnd(h)) {
      return nh;
    }
  }
  return kInvalidId;
}
References HEnd(), HNext(), HStart(), TL::kInvalidId, and VStartings().
Referenced by BoundaryHalfedges(), EdgeIsManifold(), FlipHalfedgeWithOpposite(), FNeighbors(), HConnectionsAroundStart(), HHalfedgesAroundHole(), HNextAroundEnd(), HNextAroundStart(), HPrevAroundEnd(), and HPrevAroundStart().
HPrev()
H TL::Trimesh::HPrev (H h) const inline
Returns the previous halfedge in the face.
Parameters
h The current halfedge.
Returns
The previous halfedge in the face.
Definition at line 588 of file Trimesh.hpp.
{
  assert(h < NumHalfedges());
  return h - h % 3 + (h + 2) % 3;
}
References NumHalfedges().
Referenced by TL::Processing::FillMeshHoles(), HNextAroundEnd(), HNextAroundStart(), SplitEdge(), VEnding(), and VEndings().
HPrevAroundEnd()
H TL::Trimesh::HPrevAroundEnd (H h) const inline
Returns the previous halfedge around the ending vertex.
Parameters
h The current halfedge.
Returns
The previous halfedge around the ending vertex.
Definition at line 613 of file Trimesh.hpp.
{ return HOpposite(HNext(h)); }
References HNext(), and HOpposite().
HPrevAroundStart()
H TL::Trimesh::HPrevAroundStart (H h) const inline
Returns the previous halfedge around the starting vertex.
Parameters
h The current halfedge.
Returns
The previous halfedge around the starting vertex.
Definition at line 607 of file Trimesh.hpp.
{
  return HOpposite(h) == kInvalidId ? kInvalidId : HNext(HOpposite(h));
}
References HNext(), HOpposite(), and TL::kInvalidId.
Referenced by HConnectionsAroundStart(), and HHalfedgesAroundHole().
HStart()
V TL::Trimesh::HStart (H h) const inline
Returns the starting vertex of the halfedge.
Parameters
h The halfedge index.
Returns
The starting vertex index.
Definition at line 592 of file Trimesh.hpp.
{ return hStart_.at(h); }
Referenced by TL::Distance::AsymmetricHausdorff(), TL::Distance::AsymmetricMeanEuclidean(), CollapseEdge(), TL::Processing::DecimateMesh(), DisconnectFace(), EdgeHalfedges(), FBoundingBox(), FCentroid(), TL::Processing::FillMeshHoles(), FlipHalfedgeWithOpposite(), FVertices(), HCentroid(), HEnd(), HGeometry(), HOpposite(), and SplitEdge().
NumFaces()
F TL::Trimesh::NumFaces () const inline
Returns the number of faces in the mesh.
Returns
The number of faces.
Definition at line 567 of file Trimesh.hpp.
{ return NumHalfedges() / 3; }
References NumHalfedges().
Referenced by CollapseEdge(), CreateAttribute(), TL::Processing::DecimateMesh(), Faces(), FHalfedge(), TL::Processing::PrintabilityHeuristics(), RemoveFaces(), and TL::Distance::Tree::Tree().
NumHalfedges()
H TL::Trimesh::NumHalfedges () const inline
Returns the number of halfedges in the mesh.
Returns
The number of halfedges.
Definition at line 565 of file Trimesh.hpp.
{ return hStart_.size(); }
Referenced by CreateAttribute(), TL::Processing::DecimateMesh(), TL::Processing::FillMeshHoles(), Halfedges(), HFace(), HNext(), HPrev(), NumFaces(), and TL::Processing::PrintabilityHeuristics().
NumVertices()
V TL::Trimesh::NumVertices () const inline
Returns the number of vertices in the mesh.
Returns
The number of vertices.
Definition at line 566 of file Trimesh.hpp.
{ return position_.size(); }
Referenced by CollapseEdge(), CreateAttribute(), TL::Processing::DecimateMesh(), SplitEdge(), TL::Processing::TaubinSmoothing(), and Vertices().
operator=()
Trimesh & TL::Trimesh::operator= (const Trimesh & other)
Assignment operator for Trimesh.
Parameters
other The Trimesh object to assign.
Returns
A reference to the assigned Trimesh object.
Definition at line 548 of file Trimesh.hpp.
{
  if (this != &other) {
    hStart_ = other.hStart_;
    hCoStart_ = other.hCoStart_;
    vStart_ = other.vStart_;
    position_ = other.position_;
    for (auto& attr_map : attributes_) {
      attr_map.clear();
    }
    for (int i = 0; i < 3; ++i) {
      for (const auto& [key, wrapper] : other.attributes_[i]) {
        attributes_[i][key] = wrapper->clone();
      }
    }
  }
  return *this;
}
Positions() [1/2]
std::ranges::ref_view< std::vector< Vector3d > > TL::Trimesh::Positions () inline
Returns a view of the vertex positions.
Returns
A reference view of the vertex positions.
Definition at line 577 of file Trimesh.hpp.
{
  return std::views::all(position_);
}
Referenced by TL::Distance::Tree::Tree().
Positions() [2/2]
std::ranges::ref_view< std::vector< Vector3d > const > TL::Trimesh::Positions () const inline
Returns a constant view of the vertex positions.
Returns
A constant reference view of the vertex positions.
Definition at line 580 of file Trimesh.hpp.
          {
  return std::views::all(position_);
}
RemoveFace()
std::vector< V > TL::Trimesh::RemoveFace (F f)
Removes a face from the mesh.
Parameters
f The face index.
Returns
A vector of vertices removed along with the face.
Definition at line 811 of file Trimesh.hpp.
{
  std::vector<V> removed_vertices;
  for (const auto& [key, f_attr] : attributes_[kFace]) {
    f_attr->ReplaceErase(f);
  }
  for (H h : std::views::reverse(FHalfedges(f))) {
    H g = hStart_.size() - 1;
    V v = hStart_[h];
    if (vStart_[v] == h) {
      vStart_[v] = hCoStart_[h];
    } else {
      for (H he : VStartings(v)) {
        if (hCoStart_[he] == h) {
          hCoStart_[he] = hCoStart_[h];
          break;
        }
      }
    }
    if (h != g) {
      V u = hStart_[g];
      hStart_[h] = u;
      hCoStart_[h] = hCoStart_[g];
      H* p = nullptr;
      if (vStart_[u] == g) {
        p = &vStart_[u];
      } else {
        for (H he : VStartings(u)) {
          if (hCoStart_[he] == g) {
            p = &hCoStart_[he];
            break;
          }
        }
      }
      *p = h;  // replace g with h and ensure the structure remains sorted
               // from greater to lower
      for (H nh = hCoStart_[h]; hCoStart_[h] > h && hCoStart_[h] != kInvalidId;
           nh = hCoStart_[h]) {
        *p = nh;
        hCoStart_[h] = hCoStart_[nh];
        hCoStart_[nh] = h;
        p = &hCoStart_[nh];
      }
    }
    hStart_.pop_back();
    hCoStart_.pop_back();
    for (const auto& [key, h_attr] : attributes_[kHalfedge]) {
      h_attr->ReplaceErase(h);
    }
    if (vStart_[v] == kInvalidId) {
      removed_vertices.push_back(v);
      for (H he : VStartings(vStart_.size() - 1)) {
        hStart_[he] = v;
      }
      vStart_[v] = vStart_.back(), vStart_.pop_back();
      position_[v] = std::move(position_.back()), position_.pop_back();
      for (const auto& [key, v_attr] : attributes_[kVertex]) {
        v_attr->ReplaceErase(v);
      }
    }
  }
  return removed_vertices;
}
References FHalfedges(), TL::kFace, TL::kHalfedge, TL::kInvalidId, TL::kVertex, and VStartings().
Referenced by CollapseEdge(), DisconnectFace(), FlipHalfedgeWithOpposite(), RemoveFaces(), and SplitEdge().
RemoveFaces()
std::vector< V > TL::Trimesh::RemoveFaces (std::vector< F > f_set)
Removes multiple face indices from the mesh.
Parameters
f_set A vector of face indices to remove (duplicates are ignored).
Returns
A vector of vertices indices removed along with the faces in the order of deletion (vertex indices must be updated accordingly on the fly).
Definition at line 873 of file Trimesh.hpp.
{
  std::ranges::sort(faces);
  const auto [first, last] = std::ranges::unique(faces);
  faces.erase(first, last);
  std::vector<V> removed_vertices;
  for (std::size_t i = 0; i < faces.size();) {
    F f = faces[i];
    std::vector<V> removed = RemoveFace(f);
    removed_vertices.insert(removed_vertices.end(), removed.begin(),
                            removed.end());
    if (faces.back() == NumFaces()) {
      faces.pop_back();
    } else {
      i++;
    }
  }
  return removed_vertices;
}
References NumFaces(), and RemoveFace().
Referenced by TL::Processing::RemoveSelfIntersections().
SplitEdge()
void TL::Trimesh::SplitEdge (H h)
Splits an edge and the incident faces.
Parameters
h The halfedge index.
Definition at line 957 of file Trimesh.hpp.
{
  std::variant<V, Vector3d> new_p = HCentroid(h);
  std::array<std::variant<V, Vector3d>, 3> tri;
  for (H he : std::ranges::to<std::vector>(EdgeHalfedges(h))) {
    tri = {new_p, HEnd(he), HStart(HPrev(he))};
    std::rotate(tri.begin(), tri.begin() + (3 - (he % 3)) % 3, tri.end());
    AddFace(tri);
    new_p = NumVertices() - 1;
    tri = {HStart(he), new_p, HStart(HPrev(he))};
    std::rotate(tri.begin(), tri.begin() + (3 - (he % 3)) % 3, tri.end());
    AddFace(tri);
    RemoveFace(HFace(he));
  }
}
References AddFace(), EdgeHalfedges(), HCentroid(), HEnd(), HFace(), HPrev(), HStart(), NumVertices(), and RemoveFace().
VEnding()
H TL::Trimesh::VEnding (V v) const inline
Returns the ending halfedge of the vertex.
Parameters
v The vertex index.
Returns
The ending halfedge index.
Definition at line 650 of file Trimesh.hpp.
{ return HPrev(VStarting(v)); }
References HPrev(), and VStarting().
VEndings()
std::generator< H > TL::Trimesh::VEndings (V v) const
Returns a generator for the ending halfedges of the vertex.
Parameters
v The vertex index.
Returns
A generator for the ending halfedges.
Definition at line 656 of file Trimesh.hpp.
{
  for (H h : VStartings(v)) {
    co_yield HPrev(h);
  }
}
References HPrev(), and VStartings().
Vertices()
std::ranges::iota_view< V, V > TL::Trimesh::Vertices () const inline
Returns a view of the vertices in the mesh.
Returns
A range of vertex indices.
Definition at line 571 of file Trimesh.hpp.
{
  return std::views::iota(V{0}, V{NumVertices()});
}
References NumVertices().
Referenced by DisconnectFacesUntilManifoldVertices(), and TL::Processing::TaubinSmoothing().
VFaces()
auto TL::Trimesh::VFaces (TL::V v) const
Returns a view of the faces connected to the vertex.
Parameters
v The vertex index.
Returns
A view of the face indices.
Definition at line 661 of file Trimesh.hpp.
{
  return std::views::transform(VStartings(v), [this](H h) { return HFace(h); });
}
References HFace(), and VStartings().
Referenced by VNormal().
VIsManifold()
bool TL::Trimesh::VIsManifold (V v) const
Checks if the vertex is manifold.
Parameters
v The vertex index.
Returns
True if the vertex is manifold, false otherwise.
Definition at line 678 of file Trimesh.hpp.
{
  return (std::ranges::to<std::vector>(HConnectionsAroundStart(VStarting(v))))
             .size() == (std::ranges::to<std::vector>(VStartings(v))).size();
}
References HConnectionsAroundStart(), VStarting(), and VStartings().
Referenced by DisconnectFacesUntilManifoldVertices().
VNormal()
Vector3d TL::Trimesh::VNormal (V v) const
Returns the normal vector of the vertex.
Parameters
v The vertex index.
Returns
The normal vector.
Definition at line 666 of file Trimesh.hpp.
{
  Vector3d normal{Vector3d::Zero()};
  for (F f : VFaces(v)) {
    normal += FNormal(f);
  }
  return normal.normalized();
}
References FNormal(), and VFaces().
VPosition() [1/2]
Vector3d & TL::Trimesh::VPosition (V v) inline
Returns the position of the vertex.
Parameters
v The vertex index.
Returns
The position of the vertex.
Definition at line 664 of file Trimesh.hpp.
{ return position_.at(v); }
Referenced by TL::Distance::AsymmetricHausdorff(), TL::Distance::AsymmetricMeanEuclidean(), CollapseEdge(), DisconnectFace(), FBoundingBox(), FCentroid(), FPositions(), HCentroid(), HGeometry(), and TL::Processing::TaubinSmoothing().
VPosition() [2/2]
const Vector3d & TL::Trimesh::VPosition (V v) const inline
Returns the constant position of the vertex.
Parameters
v The vertex index.
Returns
The constant position of the vertex.
Definition at line 665 of file Trimesh.hpp.
{ return position_.at(v); }
VStarting()
H TL::Trimesh::VStarting (V v) const inline
Returns the starting halfedge of the vertex.
Parameters
v The vertex index.
Returns
The starting halfedge index.
Definition at line 649 of file Trimesh.hpp.
{ return vStart_.at(v); }
Referenced by DisconnectFacesUntilManifoldVertices(), VEnding(), VIsManifold(), and VStartings().
VStartings()
std::generator< H > TL::Trimesh::VStartings (V v) const
Returns a generator for the starting halfedges of the vertex.
Parameters
v The vertex index.
Returns
A generator for the starting halfedges.
Definition at line 651 of file Trimesh.hpp.
{
  for (H h = VStarting(v); h != kInvalidId; h = hCoStart_[h]) {
    co_yield h;
  }
}
References TL::kInvalidId, and VStarting().
Referenced by CollapseEdge(), TL::Processing::DecimateMesh(), DisconnectFacesUntilManifoldVertices(), EdgeHalfedges(), HOpposite(), RemoveFace(), TL::Processing::TaubinSmoothing(), VEndings(), VFaces(), VIsManifold(), and VValence().
VValence()
size_t TL::Trimesh::VValence (V v) const
Returns the valence (degree) of the vertex.
Parameters
v The vertex index.
Returns
The valence of the vertex.
Definition at line 673 of file Trimesh.hpp.
{
  size_t ans = 0;
  for ([[maybe_unused]] H h : VStartings(v)) ans++;
  return ans;
}
References VStartings().
The documentation for this class was generated from the following file:
/home/saumz/Documents/projects/TriLite/TriLite/Core/Trimesh.hpp