TriLite: TL::Processing Class Reference
TL::Processing Class Reference
#include <Processing.hpp>
Static Public Member Functions
static void DecimateMesh (Trimesh &mesh, size_t target_face_count)
External decimation function to simplify a triangular mesh.
static void FillMeshHoles (Trimesh &mesh, size_t target_hole_count=0)
Fills holes in a triangular mesh by detecting boundary edges and adding triangles.
static void TaubinSmoothing (Trimesh &mesh, int iterations=1, double lambda=0.5, double mu=-0.53)
Applies volume-preserving Laplacian smoothing (Taubin smoothing) to a triangular mesh.
static void RemoveSelfIntersections (Trimesh &mesh)
Removes self-intersections from a triangular mesh.
static void PrintabilityHeuristics (Trimesh &mesh, int niters=10)
Prepares a triangular mesh for 3D printing by iteratively closing it while applying several cleaning and repair steps (only the largest connected component is preserved).
Detailed Description
Definition at line 33 of file Processing.hpp.
Member Function Documentation
DecimateMesh()
void TL::Processing::DecimateMesh (Trimesh & mesh, size_t target_face_count) static
External decimation function to simplify a triangular mesh.
Parameters
mesh Reference to the Trimesh object to be simplified.
target_face_count The target number of faces after decimation.
Definition at line 527 of file Processing.hpp.
{
  std::vector<double> edge_lengths(mesh.NumHalfedges());
  auto compare = [&edge_lengths](H h, H g) {
    return edge_lengths[h] < edge_lengths[g] ||
           (edge_lengths[h] == edge_lengths[g] && h < g);
  };
  std::set<H, decltype(compare)> hset(compare);
  for (H h : mesh.Halfedges()) {
    edge_lengths[h] = mesh.HLength(h);
    assert(std::isfinite(edge_lengths[h]));
    hset.insert(h);
  }
  while (mesh.NumFaces() > target_face_count && !hset.empty()) {
    auto minh = *hset.begin();
    hset.erase(minh);
    if (minh >= mesh.NumHalfedges()) {
      continue;
    }
    std::array<V, 2> verts = {mesh.HStart(minh), mesh.HEnd(minh)};
    V last_vert_id = mesh.NumVertices() - 1;
    auto [rm_faces, rm_vertices] = mesh.CollapseEdge(minh);
    for (const V& rem_v : rm_vertices) {
      for (V& v : verts) {
        if (v == rem_v) {
          v = kInvalidId;
        } else if (v == last_vert_id) {
          v = rem_v;
        }
      }
      last_vert_id--;
    }
    for (F f : rm_faces) {
      for (H h : {3 * f, 3 * f + 1, 3 * f + 2}) {
        if (h < mesh.NumHalfedges()) {
          hset.erase(h);
        }
      }
    }
    for (V v : verts) {
      if (v != kInvalidId) {
        for (H h : mesh.VStartings(v)) {
          hset.erase(h);
        }
      }
    }
    for (F f : rm_faces) {
      for (H h : {3 * f, 3 * f + 1, 3 * f + 2}) {
        if (h < mesh.NumHalfedges()) {
          edge_lengths[h] = mesh.HLength(h);
          hset.insert(h);
        }
      }
    }
    for (V v : verts) {
      if (v != kInvalidId) {
        for (H h : mesh.VStartings(v)) {
          edge_lengths[h] = mesh.HLength(h);
          hset.insert(h);
        }
      }
    }
  }
}
References TL::Trimesh::CollapseEdge(), TL::Trimesh::Halfedges(), TL::Trimesh::HEnd(), TL::Trimesh::HLength(), TL::Trimesh::HStart(), TL::kInvalidId, TL::Trimesh::NumFaces(), TL::Trimesh::NumHalfedges(), TL::Trimesh::NumVertices(), and TL::Trimesh::VStartings().
FillMeshHoles()
void TL::Processing::FillMeshHoles (Trimesh & mesh, size_t target_hole_count = 0) static
Fills holes in a triangular mesh by detecting boundary edges and adding triangles.
Parameters
mesh The triangular mesh to be processed.
Definition at line 591 of file Processing.hpp.
{
  std::unordered_set<H> boundary_edges;
  std::vector<std::vector<H>> polygons;
  for (H st_h : mesh.BoundaryHalfedges()) {
    if (!boundary_edges.count(st_h)) {
      polygons.push_back(
          std::ranges::to<std::vector>(mesh.HHalfedgesAroundHole(st_h)));
      boundary_edges.insert(polygons.back().begin(), polygons.back().end());
    }
  }
  std::sort(polygons.begin(), polygons.end(),
            [](auto& A, auto& B) { return A.size() < B.size(); });
  for (const auto& [id, polygon] : std::views::enumerate(polygons)) {
    if (polygons.size() - id == target_hole_count) {
      break;
    }
    assert(polygon.size() >= 3);
    std::vector<double> sum_angle(polygon.size());
    auto set_sum_angle = [&mesh, &polygon, &sum_angle](size_t i) {
      H h = polygon[i];
      sum_angle[i] = 0;
      for (H he : mesh.HConnectionsAroundStart(h)) {
        sum_angle[i] += std::acos(
            std::clamp(mesh.HGeometry(he).normalized().dot(
                           -mesh.HGeometry(mesh.HPrev(he)).normalized()),
                       -1.0, 1.0));
      }
    };
    auto cmp = [&mesh, &sum_angle](std::pair<size_t, double> a,
                                   std::pair<size_t, double> b) {
      return a.second < b.second;
    };
    std::priority_queue<std::pair<size_t, double>,
                        std::vector<std::pair<size_t, double>>, decltype(cmp)>
        q(cmp);
    for (size_t i = 0; i < polygon.size(); i++) {
      set_sum_angle(i);
      q.push(std::make_pair(i, sum_angle[i]));
    }
    std::set<std::pair<size_t, H>> s;
    for (size_t i = 0; i < polygon.size(); i++) {
      s.insert(std::make_pair(i, polygon[i]));
    }
    while (!q.empty() && s.size() >= 3) {
      auto [i1, angle] = q.top();
      q.pop();
      if (angle != sum_angle[i1]) {
        continue;
      }
      H h1 = polygon[i1];
      auto it = s.find(std::make_pair(i1, h1));
      if (it == s.end()) {
        continue;
      }
      auto [i0, h0] = *((it == s.begin()) ? std::prev(s.end()) : std::prev(it));
      auto [i2, h2] = *((std::next(it) == s.end()) ? s.begin() : std::next(it));
      mesh.AddFace({mesh.HStart(h0), mesh.HStart(h2), mesh.HStart(h1)});
      sum_angle[i0] += std::acos(std::clamp(
          mesh.HGeometry(mesh.NumHalfedges() - 3)
              .normalized()
              .dot(-mesh.HGeometry(mesh.NumHalfedges() - 1).normalized()),
          -1.0, 1.0));
      q.push(std::make_pair(i0, sum_angle[i0]));
      sum_angle[i2] += std::acos(std::clamp(
          mesh.HGeometry(mesh.NumHalfedges() - 2)
              .normalized()
              .dot(-mesh.HGeometry(mesh.NumHalfedges() - 3).normalized()),
          -1.0, 1.0));
      q.push(std::make_pair(i2, sum_angle[i2]));
      s.erase(it);
    }
  }
}
References TL::Trimesh::AddFace(), TL::Trimesh::BoundaryHalfedges(), TL::Trimesh::HConnectionsAroundStart(), TL::Trimesh::HGeometry(), TL::Trimesh::HHalfedgesAroundHole(), TL::Trimesh::HPrev(), TL::Trimesh::HStart(), and TL::Trimesh::NumHalfedges().
Referenced by PrintabilityHeuristics().
PrintabilityHeuristics()
void TL::Processing::PrintabilityHeuristics (Trimesh & mesh, int niters = 10) static
Prepares a triangular mesh for 3D printing by iteratively closing it while applying several cleaning and repair steps (only the largest connected component is preserved).
Parameters
mesh Reference to the Trimesh object to be prepared.
niters The number of iterations to perform (default is 10).
Definition at line 714 of file Processing.hpp.
{
  if (mesh.NumFaces() == 0) {
    return;
  }
  RetainLargestComponent(mesh);
  std::vector<double> lengths(mesh.NumHalfedges());
  for (H h : mesh.Halfedges()) {
    lengths[h] = mesh.HLength(h);
  }
  std::sort(lengths.begin(), lengths.end());
  double max_length = 2.0 * lengths[lengths.size() / 2];
  double min_length = 0.5 * lengths[lengths.size() / 2];
  for (int i = 0; i < niters; i++) {
    ClampEdgeLengths(mesh, min_length, max_length);
    TL::Processing::RemoveSelfIntersections(mesh);
    mesh.DisconnectFacesUntilManifold();
    RetainLargestComponent(mesh);
    TL::Processing::FillMeshHoles(mesh, 0);
    mesh.DisconnectFacesUntilManifold();
    RetainLargestComponent(mesh);
    MakeDelaunay(mesh);
    TL::Processing::TaubinSmoothing(mesh);
  }
}
References TL::Trimesh::DisconnectFacesUntilManifold(), FillMeshHoles(), TL::Trimesh::Halfedges(), TL::Trimesh::HLength(), TL::Trimesh::NumFaces(), TL::Trimesh::NumHalfedges(), RemoveSelfIntersections(), and TaubinSmoothing().
RemoveSelfIntersections()
void TL::Processing::RemoveSelfIntersections (Trimesh & mesh) static
Removes self-intersections from a triangular mesh.
Parameters
mesh The triangular mesh to be processed.
Definition at line 706 of file Processing.hpp.
{
  std::vector<TL::F> rm_faces;
  for (TL::F f : FindSelfIntersections(mesh)) {
    rm_faces.push_back(f);
  }
  mesh.RemoveFaces(rm_faces);
}
References TL::Trimesh::RemoveFaces().
Referenced by PrintabilityHeuristics().
TaubinSmoothing()
void TL::Processing::TaubinSmoothing (Trimesh & mesh, int iterations = 1, double lambda = 0.5, double mu = -0.53) static
Applies volume-preserving Laplacian smoothing (Taubin smoothing) to a triangular mesh.
Parameters
mesh The triangular mesh to be smoothed.
iterations The number of smoothing iterations.
lambda The smoothing factor for the Laplacian step.
mu The inverse smoothing factor for the inverse Laplacian step.
Definition at line 667 of file Processing.hpp.
{
  std::vector<Vector3d> new_positions(mesh.NumVertices());
  for (int iter = 0; iter < iterations; ++iter) {
    // Laplacian smoothing step (positive weight)
    for (V v : mesh.Vertices()) {
      Vector3d laplacian(0, 0, 0);
      size_t valence = 0;
      for (H h : mesh.VStartings(v)) {
        laplacian += mesh.VPosition(mesh.HEnd(h));
        ++valence;
      }
      laplacian /= static_cast<double>(valence);
      new_positions[v] =
          mesh.VPosition(v) + lambda * (laplacian - mesh.VPosition(v));
    }
    for (V v : mesh.Vertices()) {
      mesh.VPosition(v) = new_positions[v];
    }
    // Laplacian smoothing step (negative weight, inverse smoothing)
    for (V v : mesh.Vertices()) {
      Vector3d laplacian(0, 0, 0);
      size_t valence = 0;
      for (H h : mesh.VStartings(v)) {
        laplacian += mesh.VPosition(mesh.HEnd(h));
        ++valence;
      }
      laplacian /= static_cast<double>(valence);
      new_positions[v] =
          mesh.VPosition(v) + mu * (laplacian - mesh.VPosition(v));
    }
    for (V v : mesh.Vertices()) {
      mesh.VPosition(v) = new_positions[v];
    }
  }
}
References TL::Trimesh::HEnd(), TL::Trimesh::NumVertices(), TL::Trimesh::Vertices(), TL::Trimesh::VPosition(), and TL::Trimesh::VStartings().
Referenced by PrintabilityHeuristics().
The documentation for this class was generated from the following file:
/home/saumz/Documents/projects/TriLite/TriLite/Modules/Processing.hpp