TriLite: TL::Distance::Tree Class Reference
TL::Distance::Tree Class Reference
#include <Distance.hpp>
Public Member Functions
Tree (const Trimesh &mesh)
Constructs a Tree object with a given triangle mesh.
double Distance (const Vector3d &point)
Computes the unsigned Euclidean distance from a given point to the nearest point on the mesh.
Vector3d ClosestPoint (const Vector3d &point)
Finds the closest point on the mesh to a given point.
Detailed Description
Definition at line 112 of file Distance.hpp.
Constructor & Destructor Documentation
Tree()
TL::Distance::Tree::Tree (const Trimesh & mesh)
Constructs a Tree object with a given triangle mesh.
Constructor that initializes the Tree object with a given triangle mesh.
Parameters
mesh The triangle mesh used to construct the tree.
Definition at line 394 of file Distance.hpp.
{
  std::vector<Vector3d> vertices;
  for (const Vector3d& p : mesh.Positions()) {
    vertices.push_back({p[0], p[1], p[2]});
  }
  std::vector<std::array<int, 3>> triangles(mesh.NumFaces());
  for (F f : mesh.Faces()) {
    for (auto [i, v] : std::views::enumerate(mesh.FVertices(f))) {
      triangles[f][i] = v;
    }
  }
  this->Construct(vertices, triangles);
}
References TL::Trimesh::Faces(), TL::Trimesh::FVertices(), TL::Trimesh::NumFaces(), and TL::Trimesh::Positions().
Member Function Documentation
ClosestPoint()
Vector3d TL::Distance::Tree::ClosestPoint (const Vector3d & point)
Finds the closest point on the mesh to a given point.
This method finds the closest point on the mesh to a given point.
Parameters
point The point from which the closest point on the mesh is found.
Returns
Vector3d The closest point on the mesh to the given point.
Definition at line 410 of file Distance.hpp.
{
  Vector3d p = UnsignedResult(point).nearestPoint_;
  return {p[0], p[1], p[2]};
}
Distance()
double TL::Distance::Tree::Distance (const Vector3d & point)
Computes the unsigned Euclidean distance from a given point to the nearest point on the mesh.
This method computes the unsigned Euclidean distance from a given point to the nearest point on the mesh.
Parameters
point The point from which the distance to the mesh is calculated.
Returns
double The unsigned distance from the given point to the closest point on the mesh.
Definition at line 407 of file Distance.hpp.
{
  return UnsignedResult(point).distance_;
}
Referenced by TL::Distance::AsymmetricHausdorff(), and TL::Distance::AsymmetricMeanEuclidean().
The documentation for this class was generated from the following file:
/home/saumz/Documents/projects/TriLite/TriLite/Modules/Distance.hpp