TriLite: TL Namespace Reference
TL Namespace Reference
Classes
class Distance
class IO
class Processing
class Trimesh
Represents a triangle mesh using a half-edge data structure.
Typedefs
using Index = unsigned int
using H = Index
using V = Index
using F = Index
Enumerations
enum MeshComponent { kHalfedge , kVertex , kFace }
Variables
constexpr Index kInvalidId = std::numeric_limits<Index>::max()
Typedef Documentation
F
using TL::F = Index
Definition at line 38 of file Trimesh.hpp.
H
using TL::H = Index
Definition at line 36 of file Trimesh.hpp.
Index
using TL::Index = unsigned int
Definition at line 35 of file Trimesh.hpp.
V
using TL::V = Index
Definition at line 37 of file Trimesh.hpp.
Enumeration Type Documentation
MeshComponent
enum TL::MeshComponent
Enumerator
kHalfedge
kVertex
kFace
Definition at line 34 of file Trimesh.hpp.
{ kHalfedge, kVertex, kFace };
Variable Documentation
kInvalidId
constexpr Index TL::kInvalidId = std::numeric_limits<Index>::max() constexpr
Definition at line 39 of file Trimesh.hpp.
Referenced by TL::Trimesh::AddFace(), TL::Trimesh::BoundaryHalfedges(), TL::Trimesh::CollapseEdge(), TL::Processing::DecimateMesh(), TL::Trimesh::FlipHalfedgeWithOpposite(), TL::Trimesh::FNeighbors(), TL::Trimesh::HConnectionsAroundStart(), TL::Trimesh::HHalfedgesAroundHole(), TL::Trimesh::HNextAroundEnd(), TL::Trimesh::HOpposite(), TL::Trimesh::HPrevAroundStart(), TL::Trimesh::RemoveFace(), and TL::Trimesh::VStartings().